---
services:
  pg_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-my_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-my_password}
      POSTGRES_DB: ${POSTGRES_DB:-my_db}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-my_user}"]
      interval: 10s
      timeout: 2s
      retries: 10

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://my_user:my_password@pg_db/my_db?sslmode=disable
    depends_on:
      pg_db:
        condition: service_healthy
